input: touchscreen: st: Don't redefine u8, u16, and u32
Clang warns:

../drivers/input/touchscreen/st/fts_lib/ftsSoftware.h:18:23: warning:
redefinition of typedef 'u8' is a C11 feature [-Wtypedef-redefinition]
../drivers/input/touchscreen/st/fts_lib/ftsSoftware.h:19:24: warning:
redefinition of typedef 'u16' is a C11 feature [-Wtypedef-redefinition]
../drivers/input/touchscreen/st/fts_lib/ftsSoftware.h:20:22: warning:
redefinition of typedef 'u32' is a C11 feature [-Wtypedef-redefinition]

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
(cherry picked from commit 5afa0f71d5df61516e1fb9e3b91fe23dedfa954a)
(cherry picked from commit 341c9ac2f7a58b1a3427e6a0f575e928c3e65854)